import {test,after} from 'node:test';import assert from 'node:assert/strict';import handler from '../api/index.js';
const originalFetch=globalThis.fetch;after(()=>{globalThis.fetch=originalFetch});process.env.SUPABASE_URL='https://fixture.invalid';process.env.SUPABASE_PUBLISHABLE_KEY='test-public-key';
const user={id:'11111111-1111-4111-8111-111111111111',user_metadata:{pipvoria_settings:{timezone:'Europe/Paris',confirmedOnly:true}}};const id='22222222-2222-4222-8222-222222222222';const payload={symbol:'XAU/USD',interval:'5min',status:'win',closedAt:Date.now(),resultR:2,clientUpdatedAt:Date.now()};
const response=(v,status=200)=>new Response(JSON.stringify(v),{status});
const request=(route,data,method=data?'POST':'GET')=>new Request('https://site.invalid/api?route='+route,{method,headers:{cookie:'blh_access=test-token',origin:'https://site.invalid','content-type':'application/json'},body:data?JSON.stringify(data):undefined});
function mock(run){globalThis.fetch=async(url,init={})=>String(url).endsWith('/auth/v1/user')&&(!init.method||init.method==='GET')?response(user):run(String(url),init)}
test('account settings use validated session and metadata only',async()=>{mock((url,init)=>{assert.equal(init.method,'PUT');assert.equal(new Headers(init.headers).get('authorization'),'Bearer test-token');const data=JSON.parse(init.body);assert.ok(data.data.pipvoria_settings);assert.equal(data.app_metadata,undefined);return response(user)});const get=await handler(request('settings'));assert.equal((await get.json()).settings.timezone,'Europe/Paris');assert.equal((await handler(request('settings',{settings:{timezone:'UTC'}}))).status,200)});
test('cross-origin settings mutation rejected',async()=>{const req=new Request('https://site.invalid/api?route=settings',{method:'POST',headers:{origin:'https://other.invalid','content-type':'application/json'},body:'{}'});assert.equal((await handler(req)).status,404)});
test('CAS update scopes owner and returns newer server version on conflict',async()=>{let calls=0;const entry={id,updated_at:new Date().toISOString(),payload};mock((url,init)=>{calls++;assert.ok(url.includes('user_id=eq.'+user.id));if(init.method==='PATCH'){assert.ok(url.includes('updated_at=eq.'));return response([])}return response([entry])});const r=await handler(request('journal/update&id='+id,{kind:'trade',payload,baseUpdatedAt:'2026-10-01T12:00:00Z'}));assert.equal(r.status,409);assert.equal((await r.json()).entry.id,id);assert.equal(calls,2)});
test('update without revision does not write',async()=>{mock(()=>{assert.fail('must not write')});assert.equal((await handler(request('journal/update&id='+id,{payload}))).status,409)});
test('idempotent create preserves successful prior write',async()=>{mock((url,init)=>init.method==='POST'?response([]):response([{id,payload}]));const r=await handler(request('journal/create',{id,kind:'trade',payload}));assert.equal(r.status,200);assert.equal((await r.json()).entry.id,id)});
test('different retry revision yields conflict, never overwrites',async()=>{mock((url,init)=>init.method==='POST'?response([]):response([{id,payload:{...payload,clientUpdatedAt:1}}]));assert.equal((await handler(request('journal/create',{id,payload}))).status,409)});
test('unknown results stay null and closure timestamp is saved',async()=>{mock((url,init)=>{const data=JSON.parse(init.body);assert.equal(data.payload.resultR,null);assert.equal(data.payload.closedAt,payload.closedAt);return response([{id,payload:data.payload}])});assert.equal((await handler(request('journal/create',{id,payload:{...payload,resultR:null}}))).status,201)});
test('logout confirms cookie clearing even if upstream is unavailable',async()=>{mock(()=>{throw Error('offline')});const r=await handler(request('auth/sign-out',{}));assert.equal(r.status,200);assert.equal((await r.json()).signedOut,true);assert.ok(r.headers.get('set-cookie').includes('Max-Age=0'))});
test('gold failure never calls PAXG fallback and Yahoo uses 1m',async()=>{const calls=[];mock(url=>{calls.push(url);return response({error:'unavailable'},503)});const r=await handler(request('gold&interval=1min'));assert.equal(r.status,503);assert.ok(calls.some(u=>u.includes('interval=1m&')));assert.ok(calls.every(u=>!u.includes('PAXG')&&!u.includes('binance')))});
test('invalid dates, results and risk are rejected rather than silently discarded',async()=>{mock(()=>assert.fail('must not write'));for(const bad of [{closedAt:Date.now()+86400000},{riskPercent:200},{resultR:1001}])assert.equal((await handler(request('journal/create',{id,payload:{...payload,...bad}}))).status,400)});
test('unavailable provider yields structured response, not an unhandled rejection',async()=>{globalThis.fetch=async()=>{throw Error('offline')};const r=await handler(request('settings'));assert.equal(r.status,500);assert.equal((await r.json()).error,'server_error')});
