import http from 'node:http';import fs from 'node:fs';import path from 'node:path';const root=path.resolve(process.argv[2]);let signedIn=true,failLogout=false,failJournal=false,settings={},notifications=[],preferences={};const now=Date.now();let revision=now;
const journal=[{id:'22222222-2222-4222-8222-222222222222',kind:'trade',created_at:new Date(now-8*86400000).toISOString(),updated_at:new Date(now).toISOString(),payload:{symbol:'XAU/USD',interval:'5min',status:'win',strategy:'planner',direction:'buy',entry:4200,stopLoss:4190,takeProfits:[4210,4220,4230],targetHits:[true,true,false],resultR:2,riskPercent:1,closedAt:now-5000,notes:'Fixture closed today'}},{id:'33333333-3333-4333-8333-333333333333',kind:'trade',created_at:new Date(now-3600000).toISOString(),updated_at:new Date(now).toISOString(),payload:{symbol:'XAU/USD',interval:'5min',status:'active',strategy:'planner',direction:'sell',entry:4230,stopLoss:4240,takeProfits:[4220,4210,4200],targetHits:[true,false,false],riskPercent:1,positionSize:.1,resultR:null,notes:''}}];
function makeBars(frame){const dur={'1min':60000,'5min':300000,'15min':900000,'30min':1800000,'1h':3600000}[frame]||300000;return Array.from({length:220},(_,i)=>{const close=4200+Math.sin(i/8)*20+i/7;return{time:Math.floor(Date.now()/dur)*dur-(219-i)*dur,open:close-2,high:close+5,low:close-5,close,volume:100+i,closed:i<219}})}
http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');const json=(data,status=200)=>{res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(data))};
if(url.pathname==='/__verify'){if(url.searchParams.has('reset'))signedIn=true;if(url.searchParams.has('failLogout'))failLogout=url.searchParams.get('failLogout')==='1';if(url.searchParams.has('failJournal'))failJournal=url.searchParams.get('failJournal')==='1';if(url.searchParams.has('conflict')){const row=journal.find(r=>r.id===url.searchParams.get('conflict'));row.updated_at=new Date(++revision).toISOString();row.payload.notes='Remote conflict'}return json({signedIn,failJournal,failLogout,journal,notifications,settings})}
if(url.pathname==='/api/stream'){res.writeHead(200,{'content-type':'text/event-stream'});res.write(': fixture\n\n');const t=setInterval(()=>res.write(': keepalive\n\n'),10000);req.on('close',()=>clearInterval(t));return}
if(url.pathname==='/api'){const route=url.searchParams.get('route');let data={};if(req.method==='POST'){let text='';for await(const chunk of req)text+=chunk;data=JSON.parse(text||'{}')}
 if(route==='auth/session')return json(signedIn?{user:{id:'11111111-1111-4111-8111-111111111111',name:'Vérification',email:'fixture@example.invalid',role:'user'}}:{},signedIn?200:401);
 if(route==='auth/sign-out'){if(failLogout)return json({error:'fixture_offline'},503);signedIn=false;return json({signedOut:true})}
 if(route==='settings'){if(req.method==='POST')settings=data.settings;return json({settings})}
 if(route==='profile/avatar'){res.writeHead(404);return res.end()}
 if(route==='workspace')return json({journal,notifications,preferences});
 if(route==='preferences'){preferences=data;return json({preferences})}
 if(route==='journal/create'||route==='journal/update'){if(failJournal)return json({error:'offline'},503);const id=route==='journal/create'?data.id:url.searchParams.get('id'),found=journal.find(r=>r.id===id);if(found&&((route==='journal/update'&&found.updated_at!==data.baseUpdatedAt)||(route==='journal/create'&&found.payload.clientUpdatedAt!==data.payload.clientUpdatedAt)))return json({error:'journal_conflict',entry:found},409);const row={id,kind:data.kind,created_at:found?.created_at||new Date().toISOString(),updated_at:new Date(Math.max(Date.now(),++revision)).toISOString(),payload:data.payload};if(found)journal.splice(journal.indexOf(found),1,row);else journal.unshift(row);return json({entry:row})}
 if(route==='notifications/create'){if(!notifications.some(n=>n.signal_key===data.signalKey))notifications.unshift({...data,signal_key:data.signalKey,created_at:new Date().toISOString(),is_read:false});return json({notification:notifications[0]})}
 if(route==='notifications/read'){notifications.forEach(n=>n.is_read=true);return json({updated:true})}
 if(route==='gold'){const interval=url.searchParams.get('interval');return json({symbol:'XAU/USD',interval,source:'Test fixture (synthetic)',volumeMode:'provider',fetchedAt:Date.now(),bars:makeBars(interval)})}
 if(route==='gold/price')return json({price:makeBars('5min').at(-1).close,receivedAt:Date.now(),source:'Test fixture (synthetic)'});
 return json({ok:true})}
const target=path.resolve(root,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));if(!target.startsWith(root+path.sep)){res.writeHead(403);return res.end()}try{const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.mp4':'video/mp4','.webmanifest':'application/manifest+json'};let data=fs.readFileSync(target);if(path.extname(target)==='.html')data=Buffer.from(data.toString().replace('<head>',`<head><script>window.__uiErrors=[];addEventListener('error',e=>__uiErrors.push(e.message));addEventListener('unhandledrejection',e=>__uiErrors.push(String(e.reason)));</script>`));res.writeHead(200,{'content-type':types[path.extname(target)]||'application/octet-stream','cache-control':'no-store'});res.end(data)}catch{res.writeHead(404);res.end()}}).listen(4173,'127.0.0.1',()=>console.log('Workspace fixture on http://127.0.0.1:4173'));
